### PR TITLE
Update deps.

### PR DESCRIPTION
**Pull request by dvc94ch**
quinn-proto is using rustls 0.19

### CODE REVIEW

**Comment by dvc94ch** [comment]
Would it be possible to get a release of barebones-x509?

**Comment by DemiMarie** [comment]
> Would it be possible to get a release of barebones-x509?

Will do!

**Comment by dvc94ch** [comment]
Also maybe make it a proper repo instead of a fork if this is the new home. You can reference the old one in the README for attribution.

**Comment by DemiMarie** [comment]
> > Would it be possible to get a release of barebones-x509?
> 
> Will do!

Done: https://crates.io/crates/barebones-x509

**Pull request merged**
